<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class ChefSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // J7A
        DB::table("chefs")->insert([
            "first_name" => "test0",
            "last_name" => "test0",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7A",
            "mobile" => "1111111110",
            "is_mobile_verified" => "0",
            "email" => "test0@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test0's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test1",
            "last_name" => "test1",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7A",
            "mobile" => "1111111111",
            "is_mobile_verified" => "0",
            "email" => "test1@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test2's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test2",
            "last_name" => "test2",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7A",
            "mobile" => "1111111112",
            "is_mobile_verified" => "0",
            "email" => "test2@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test2's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test3",
            "last_name" => "test3",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7A",
            "mobile" => "1111111113",
            "is_mobile_verified" => "0",
            "email" => "test3@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test3's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test4",
            "last_name" => "test4",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7A",
            "mobile" => "1111111114",
            "is_mobile_verified" => "0",
            "email" => "test4@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test4's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test5",
            "last_name" => "test5",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7A",
            "mobile" => "1111111115",
            "is_mobile_verified" => "0",
            "email" => "test5@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test5's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test6",
            "last_name" => "test6",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7A",
            "mobile" => "1111111116",
            "is_mobile_verified" => "0",
            "email" => "test6@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test6's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test7",
            "last_name" => "test7",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7A",
            "mobile" => "1111111117",
            "is_mobile_verified" => "0",
            "email" => "test7@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test7's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test8",
            "last_name" => "test8",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7A",
            "mobile" => "1111111118",
            "is_mobile_verified" => "0",
            "email" => "test8@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test8's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test9",
            "last_name" => "test9",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7A",
            "mobile" => "1111111119",
            "is_mobile_verified" => "0",
            "email" => "test9@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test9's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);

        // J7E
        DB::table("chefs")->insert([
            "first_name" => "test20",
            "last_name" => "test20",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7E",
            "mobile" => "1111111120",
            "is_mobile_verified" => "0",
            "email" => "test20@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test20's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test21",
            "last_name" => "test21",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7E",
            "mobile" => "1111111121",
            "is_mobile_verified" => "0",
            "email" => "test21@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test21's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test22",
            "last_name" => "test22",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7E",
            "mobile" => "1111111122",
            "is_mobile_verified" => "0",
            "email" => "test22@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test22's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test23",
            "last_name" => "test23",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7E",
            "mobile" => "1111111123",
            "is_mobile_verified" => "0",
            "email" => "test23@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test24",
            "last_name" => "test24",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7E",
            "mobile" => "1111111124",
            "is_mobile_verified" => "0",
            "email" => "test24@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test25",
            "last_name" => "test25",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7E",
            "mobile" => "1111111125",
            "is_mobile_verified" => "0",
            "email" => "test25@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test25's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test26",
            "last_name" => "test26",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7E",
            "mobile" => "1111111126",
            "is_mobile_verified" => "0",
            "email" => "test26@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test26's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test27",
            "last_name" => "test27",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7E",
            "mobile" => "1111111127",
            "is_mobile_verified" => "0",
            "email" => "test27@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test27's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test28",
            "last_name" => "test28",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7E",
            "mobile" => "1111111128",
            "is_mobile_verified" => "0",
            "email" => "test28@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test28's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test29",
            "last_name" => "test29",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7E",
            "mobile" => "1111111129",
            "is_mobile_verified" => "0",
            "email" => "test29@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test29's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);

        // H7N
        DB::table("chefs")->insert([
            "first_name" => "test30",
            "last_name" => "test30",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "H7N",
            "mobile" => "1111111130",
            "is_mobile_verified" => "0",
            "email" => "test30@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test30's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test31",
            "last_name" => "test31",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "H7N",
            "mobile" => "1111111131",
            "is_mobile_verified" => "0",
            "email" => "test31@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test31's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test32",
            "last_name" => "test32",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "H7N",
            "mobile" => "1111111132",
            "is_mobile_verified" => "0",
            "email" => "test32@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test32's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test33",
            "last_name" => "test33",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "H7N",
            "mobile" => "1111111133",
            "is_mobile_verified" => "0",
            "email" => "test33@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test3sKitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test34",
            "last_name" => "test34",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "H7N",
            "mobile" => "1111111134",
            "is_mobile_verified" => "0",
            "email" => "test34@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test3sKitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test35",
            "last_name" => "test35",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "H7N",
            "mobile" => "1111111135",
            "is_mobile_verified" => "0",
            "email" => "test35@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test35's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test36",
            "last_name" => "test36",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "H7N",
            "mobile" => "1111111136",
            "is_mobile_verified" => "0",
            "email" => "test36@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test36's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test37",
            "last_name" => "test37",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "H7N",
            "mobile" => "1111111137",
            "is_mobile_verified" => "0",
            "email" => "test37@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test37's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test38",
            "last_name" => "test38",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "H7N",
            "mobile" => "1111111138",
            "is_mobile_verified" => "0",
            "email" => "test38@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test38's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test39",
            "last_name" => "test39",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "H7N",
            "mobile" => "1111111139",
            "is_mobile_verified" => "0",
            "email" => "test39@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test39's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);

        // H7W
        DB::table("chefs")->insert([
            "first_name" => "test40",
            "last_name" => "test40",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "H7w",
            "mobile" => "1111111140",
            "is_mobile_verified" => "0",
            "email" => "test40@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test40's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test41",
            "last_name" => "test41",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "H7w",
            "mobile" => "1111111141",
            "is_mobile_verified" => "0",
            "email" => "test41@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test41's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test42",
            "last_name" => "test42",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "H7w",
            "mobile" => "1111111142",
            "is_mobile_verified" => "0",
            "email" => "test42@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test42's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test43",
            "last_name" => "test43",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "H7w",
            "mobile" => "1111111143",
            "is_mobile_verified" => "0",
            "email" => "test43@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test4sKitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test44",
            "last_name" => "test44",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "H7w",
            "mobile" => "1111111144",
            "is_mobile_verified" => "0",
            "email" => "test44@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test4sKitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test45",
            "last_name" => "test45",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "H7w",
            "mobile" => "1111111145",
            "is_mobile_verified" => "0",
            "email" => "test45@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test45's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test46",
            "last_name" => "test46",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "H7w",
            "mobile" => "1111111146",
            "is_mobile_verified" => "0",
            "email" => "test46@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test46's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test47",
            "last_name" => "test47",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "H7w",
            "mobile" => "1111111147",
            "is_mobile_verified" => "0",
            "email" => "test47@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test47's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test48",
            "last_name" => "test48",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "H7w",
            "mobile" => "1111111148",
            "is_mobile_verified" => "0",
            "email" => "test48@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test48's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test49",
            "last_name" => "test49",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "H7w",
            "mobile" => "1111111149",
            "is_mobile_verified" => "0",
            "email" => "test49@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test49's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);

        // H7L
        DB::table("chefs")->insert([
            "first_name" => "test50",
            "last_name" => "test50",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "H7L",
            "mobile" => "1111111150",
            "is_mobile_verified" => "0",
            "email" => "test50@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test50's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test51",
            "last_name" => "test51",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "H7L",
            "mobile" => "1111111151",
            "is_mobile_verified" => "0",
            "email" => "test51@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test51's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test52",
            "last_name" => "test52",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "H7L",
            "mobile" => "1111111152",
            "is_mobile_verified" => "0",
            "email" => "test52@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test52's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test53",
            "last_name" => "test53",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "H7L",
            "mobile" => "1111111153",
            "is_mobile_verified" => "0",
            "email" => "test53@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test5sKitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test54",
            "last_name" => "test54",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "H7L",
            "mobile" => "1111111154",
            "is_mobile_verified" => "0",
            "email" => "test54@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test5sKitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test55",
            "last_name" => "test55",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "H7L",
            "mobile" => "1111111155",
            "is_mobile_verified" => "0",
            "email" => "test55@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test55's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test56",
            "last_name" => "test56",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "H7L",
            "mobile" => "1111111156",
            "is_mobile_verified" => "0",
            "email" => "test56@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test56's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test57",
            "last_name" => "test57",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "H7L",
            "mobile" => "1111111157",
            "is_mobile_verified" => "0",
            "email" => "test57@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test57's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test58",
            "last_name" => "test58",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "H7L",
            "mobile" => "1111111158",
            "is_mobile_verified" => "0",
            "email" => "test58@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test58's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test59",
            "last_name" => "test59",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "H7L",
            "mobile" => "1111111159",
            "is_mobile_verified" => "0",
            "email" => "test59@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test59's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);

        // J7B
        DB::table("chefs")->insert([
            "first_name" => "test60",
            "last_name" => "test60",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7B",
            "mobile" => "1111111160",
            "is_mobile_verified" => "0",
            "email" => "test60@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test60's  Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test61",
            "last_name" => "test61",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7B",
            "mobile" => "1111111161",
            "is_mobile_verified" => "0",
            "email" => "test61@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test61's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test62",
            "last_name" => "test62",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7B",
            "mobile" => "1111111162",
            "is_mobile_verified" => "0",
            "email" => "test62@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test62's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test63",
            "last_name" => "test63",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7B",
            "mobile" => "1111111163",
            "is_mobile_verified" => "0",
            "email" => "test63@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test5sKitch6n",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test64",
            "last_name" => "test64",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7B",
            "mobile" => "1111111164",
            "is_mobile_verified" => "0",
            "email" => "test64@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test5sKitch6n",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test65",
            "last_name" => "test65",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7B",
            "mobile" => "1111111165",
            "is_mobile_verified" => "0",
            "email" => "test65@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test65's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test66",
            "last_name" => "test66",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7B",
            "mobile" => "1111111166",
            "is_mobile_verified" => "0",
            "email" => "test66@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test66's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test67",
            "last_name" => "test67",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7B",
            "mobile" => "1111111167",
            "is_mobile_verified" => "0",
            "email" => "test67@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test67's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test68",
            "last_name" => "test68",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7B",
            "mobile" => "1111111168",
            "is_mobile_verified" => "0",
            "email" => "test68@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test68's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test69",
            "last_name" => "test69",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7B",
            "mobile" => "1111111169",
            "is_mobile_verified" => "0",
            "email" => "test69@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test69's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);

        // J7H
        DB::table("chefs")->insert([
            "first_name" => "test70",
            "last_name" => "test70",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7H",
            "mobile" => "1111111170",
            "is_mobile_verified" => "0",
            "email" => "test70@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test70's  Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test71",
            "last_name" => "test71",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7H",
            "mobile" => "1111111171",
            "is_mobile_verified" => "0",
            "email" => "test71@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test71's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test72",
            "last_name" => "test72",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7H",
            "mobile" => "1111111172",
            "is_mobile_verified" => "0",
            "email" => "test72@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test72's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test73",
            "last_name" => "test73",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7H",
            "mobile" => "1111111173",
            "is_mobile_verified" => "0",
            "email" => "test73@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test5sKitch7n",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test74",
            "last_name" => "test74",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7H",
            "mobile" => "1111111174",
            "is_mobile_verified" => "0",
            "email" => "test74@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test5sKitch7n",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test75",
            "last_name" => "test75",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7H",
            "mobile" => "1111111175",
            "is_mobile_verified" => "0",
            "email" => "test75@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test75's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test76",
            "last_name" => "test76",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7H",
            "mobile" => "1111111176",
            "is_mobile_verified" => "0",
            "email" => "test76@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test76's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test77",
            "last_name" => "test77",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7H",
            "mobile" => "1111111177",
            "is_mobile_verified" => "0",
            "email" => "test77@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test77's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test78",
            "last_name" => "test78",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7H",
            "mobile" => "1111111178",
            "is_mobile_verified" => "0",
            "email" => "test78@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test78's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test79",
            "last_name" => "test79",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7H",
            "mobile" => "1111111179",
            "is_mobile_verified" => "0",
            "email" => "test79@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test79's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);

        // J6Z
        DB::table("chefs")->insert([
            "first_name" => "test80",
            "last_name" => "test80",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J6Z",
            "mobile" => "1111111180",
            "is_mobile_verified" => "0",
            "email" => "test80@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test80's  Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test81",
            "last_name" => "test81",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J6Z",
            "mobile" => "1111111181",
            "is_mobile_verified" => "0",
            "email" => "test81@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test81's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test82",
            "last_name" => "test82",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J6Z",
            "mobile" => "1111111182",
            "is_mobile_verified" => "0",
            "email" => "test82@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test82's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test83",
            "last_name" => "test83",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J6Z",
            "mobile" => "1111111183",
            "is_mobile_verified" => "0",
            "email" => "test83@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test5sKitch8n",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test84",
            "last_name" => "test84",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J6Z",
            "mobile" => "1111111184",
            "is_mobile_verified" => "0",
            "email" => "test84@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test5sKitch8n",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test85",
            "last_name" => "test85",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J6Z",
            "mobile" => "1111111185",
            "is_mobile_verified" => "0",
            "email" => "test85@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test85's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test86",
            "last_name" => "test86",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J6Z",
            "mobile" => "1111111186",
            "is_mobile_verified" => "0",
            "email" => "test86@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test86's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test87",
            "last_name" => "test87",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J6Z",
            "mobile" => "1111111187",
            "is_mobile_verified" => "0",
            "email" => "test87@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test87's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test88",
            "last_name" => "test88",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J6Z",
            "mobile" => "1111111188",
            "is_mobile_verified" => "0",
            "email" => "test88@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test88's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test89",
            "last_name" => "test89",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J6Z",
            "mobile" => "1111111189",
            "is_mobile_verified" => "0",
            "email" => "test89@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test89's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);

        // J7M
        DB::table("chefs")->insert([
            "first_name" => "test90",
            "last_name" => "test90",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7M",
            "mobile" => "1111111190",
            "is_mobile_verified" => "0",
            "email" => "test90@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test90's  Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test91",
            "last_name" => "test91",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7M",
            "mobile" => "1111111191",
            "is_mobile_verified" => "0",
            "email" => "test91@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test91's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test92",
            "last_name" => "test92",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7M",
            "mobile" => "1111111192",
            "is_mobile_verified" => "0",
            "email" => "test92@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test92's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test93",
            "last_name" => "test93",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7M",
            "mobile" => "1111111193",
            "is_mobile_verified" => "0",
            "email" => "test93@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test9sKitch8n",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test94",
            "last_name" => "test94",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7M",
            "mobile" => "1111111194",
            "is_mobile_verified" => "0",
            "email" => "test94@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test9sKitch8n",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test95",
            "last_name" => "test95",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7M",
            "mobile" => "1111111195",
            "is_mobile_verified" => "0",
            "email" => "test95@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test95's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test96",
            "last_name" => "test96",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7M",
            "mobile" => "1111111196",
            "is_mobile_verified" => "0",
            "email" => "test96@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test96's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test97",
            "last_name" => "test97",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7M",
            "mobile" => "1111111197",
            "is_mobile_verified" => "0",
            "email" => "test97@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test97's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test98",
            "last_name" => "test98",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7M",
            "mobile" => "1111111198",
            "is_mobile_verified" => "0",
            "email" => "test98@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test98's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test99",
            "last_name" => "test99",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7M",
            "mobile" => "1111111199",
            "is_mobile_verified" => "0",
            "email" => "test99@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test99's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);

        // H7P
        DB::table("chefs")->insert([
            "first_name" => "test100",
            "last_name" => "test100",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "H7P",
            "mobile" => "1111111100",
            "is_mobile_verified" => "0",
            "email" => "test100@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test100's  Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test101",
            "last_name" => "test101",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "H7P",
            "mobile" => "1111111101",
            "is_mobile_verified" => "0",
            "email" => "test101@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test101's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test102",
            "last_name" => "test102",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "H7P",
            "mobile" => "1111111102",
            "is_mobile_verified" => "0",
            "email" => "test102@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test102's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test103",
            "last_name" => "test103",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "H7P",
            "mobile" => "1111111103",
            "is_mobile_verified" => "0",
            "email" => "test103@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test9sKitch10n",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test104",
            "last_name" => "test104",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "H7P",
            "mobile" => "1111111104",
            "is_mobile_verified" => "0",
            "email" => "test104@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test9sKitch10n",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test105",
            "last_name" => "test105",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "H7P",
            "mobile" => "1111111105",
            "is_mobile_verified" => "0",
            "email" => "test105@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test105's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test106",
            "last_name" => "test106",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "H7P",
            "mobile" => "1111111106",
            "is_mobile_verified" => "0",
            "email" => "test106@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test106's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test107",
            "last_name" => "test107",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "H7P",
            "mobile" => "1111111107",
            "is_mobile_verified" => "0",
            "email" => "test107@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test107's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test108",
            "last_name" => "test108",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "H7P",
            "mobile" => "1111111108",
            "is_mobile_verified" => "0",
            "email" => "test108@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test108's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test109",
            "last_name" => "test109",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "H7P",
            "mobile" => "1111111109",
            "is_mobile_verified" => "0",
            "email" => "test109@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test109's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);

        // J7A4N7
        DB::table("chefs")->insert([
            "first_name" => "test110",
            "last_name" => "test110",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7A4N7",
            "mobile" => "1111111210",
            "is_mobile_verified" => "0",
            "email" => "test110@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test110's  Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test111",
            "last_name" => "test111",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7A4N7",
            "mobile" => "1111111211",
            "is_mobile_verified" => "0",
            "email" => "test111@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test111's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test112",
            "last_name" => "test112",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7A4N7",
            "mobile" => "1111111212",
            "is_mobile_verified" => "0",
            "email" => "test112@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test112's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test113",
            "last_name" => "test113",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7A4N7",
            "mobile" => "1111111213",
            "is_mobile_verified" => "0",
            "email" => "test113@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test9sKitch11n",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test114",
            "last_name" => "test114",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7A4N7",
            "mobile" => "1111111214",
            "is_mobile_verified" => "0",
            "email" => "test114@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test9sKitch11n",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test115",
            "last_name" => "test115",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7A4N7",
            "mobile" => "1111111215",
            "is_mobile_verified" => "0",
            "email" => "test115@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test115's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test116",
            "last_name" => "test116",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7A4N7",
            "mobile" => "1111111216",
            "is_mobile_verified" => "0",
            "email" => "test116@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test116's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test117",
            "last_name" => "test117",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7A4N7",
            "mobile" => "1111111217",
            "is_mobile_verified" => "0",
            "email" => "test117@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test117's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test118",
            "last_name" => "test118",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7A4N7",
            "mobile" => "1111111218",
            "is_mobile_verified" => "0",
            "email" => "test118@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test118's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);
        DB::table("chefs")->insert([
            "first_name" => "test119",
            "last_name" => "test119",
            "date_of_birth" => "2001-11-04",
            "postal_code" => "J7A4N7",
            "mobile" => "1111111219",
            "is_mobile_verified" => "0",
            "email" => "test119@gmail.com",
            "password" => Hash::make("Homeshef@123"),
            "kitchen_name" => "test119's Kitchen",
            "about_kitchen" => "We have 1 year of experience in cooking with all type of cuisines",
            "kitchen_types" => json_encode(["Indian", "American"]),
            "chefAvailibilityWeek" => json_encode(["Su", "M", "T", "W", "Th", "F", "S"]),
            "status" => 1,
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now()
        ]);

    }
}