<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class IngredientSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('ingredients')->insert(['ing_name' => 'salt', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'garlic', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'onion', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'turmeric', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'ginger', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'sugar', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'tomatoes', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'cumin', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'garam masala', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'coriander', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'cumin seeds', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'coriander powder', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'green chili', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'red chili powder', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'curry leaves', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'yogurt', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'cinnamon', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'oil', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'olive oil', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'black pepper', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'cardamom', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'mustard seeds', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'turmeric powder', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'water', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'butter', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'rice', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'potatoes', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'pepper', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'vegetable oil', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'cloves', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'carrots', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'canola oil', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'chicken', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'red chili', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'bay leaf', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'potato', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'soy sauce', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'milk', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'basmati rice', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'green chilies', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'coconut', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'cumin powder', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'coriander leaves', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'carrot', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'eggs', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'lemon juice', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'tamarind', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'peas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'flour', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'saffron', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'chili powder', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'lemon', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'paneer', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'bay leaves', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'coconut milk', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'cauliflower', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'mint', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'asafoetida', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'green peas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'cabbage', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'vinegar', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'coriander seeds', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'asafetida', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'green chiles', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'eggplant', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'cashews', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'whole wheat flour', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'cream', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'clove', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'raisins', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'wheat flour', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'peanuts', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'mustard', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'jaggery', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'almonds', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'fish sauce', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'tomato paste', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'star anise', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'cucumber', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'bell peppers', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'sesame oil', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'fennel seeds', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'urad dal (black gram)', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'mustard oil', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'green onion', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'sesame seeds', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'beef', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'paprika', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'coconut oil', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'parsley', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'fenugreek', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'pork', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'fenugreek seeds', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'chickpeas', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'chili', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'brown sugar', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'baking powder', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'lemongrass', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'red onion', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'corn', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'green beans', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'green chilis', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'lentils', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'tofu', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'toor dal', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'jeera', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'lime', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'cashew nuts', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'sea salt', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'lime juice', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'green cardamom', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'sunflower oil', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'heavy cream', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'black salt', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'mustard seed', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'kosher salt', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'oyster sauce', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'shallots', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'ginger garlic paste', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'fennel', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'garam masala powder', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'baking soda', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'poppy seeds', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'basil', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'nutmeg', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'celery', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'all purpose flour', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'fenugreek leaves', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'yeast', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'hing', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'himalayan pink salt', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'spices', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'jasmine rice', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'gram flour', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'ground beef', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'chana dal', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'shallot', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'condensed milk', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'rice vinegar', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'scallions', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'semolina', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'okra', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'broccoli', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'cardamom powder', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'black cardamom', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'red pepper', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'dry mango powder', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'moong dal', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'red chilies', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'green onions', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'curd', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'mint leaves', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'galangal', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'halal chicken', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'chaat masala', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'kashmiri red chili powder', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'extra virgin olive oil', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'desi ghee (clarified butter)', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'vanilla', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'rice flour', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'mace', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'whole garam masala', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'carom seeds', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'boneless chicken', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'garlic powder', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'zucchini', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'filtered water', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'red kidney beans', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'cinnamon stick', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'tomato sauce', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'white rice', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'garlic paste', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'palm sugar', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'cucumbers', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'oregano', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'milk powder', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'thyme', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'green pepper', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'dry red chili', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'iodized salt', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'corn starch', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'dry coconut', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'cumin seed', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'yoghurt', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'mushrooms', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'pumpkin', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'kidney beans', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'clarified butter', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'curry powder', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'chickpea flour', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'honey', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'fresh coriander', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'raisin', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'grated coconut', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'fresh herbs', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'cardamon', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'white pepper', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'almond', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'capsicum', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'fennel seed', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'pineapple', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'chicken breast', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'chicken breast', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'sambar powder', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'chives', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'rose water', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'pistachios', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'ginger paste', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'chilies', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'dill', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'sake', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'ginger-garlic paste', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'channa dal (chickpea lentils)', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'wheat', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'rice wine', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'ground pork', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'chili sauce', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'mirin', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'cinnamon sticks', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'pistachio', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'sour cream', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'peanut', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'dates', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'chicken thighs', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'mushroom', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'noodles', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'yellow onion', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'chicken stock', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'cottage cheese', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'dried red chili', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'fresh coconut', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'quinoa', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'evaporated milk', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'vegetables', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'banana', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'lettuce', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'radish', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'ketchup', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'ajwain', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'ground spices', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'onion powder', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'black seed', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'halal boneless chicken', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'avocado oil', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'jalapeños', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'fresh cream', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'cayenne pepper', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'buttermilk', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'garbanzo beans', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'greek yogurt', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'dried fenugreek leaves', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'fresh garlic', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'shredded coconut', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'spring onion', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'red lentils', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'vermicelli', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'himalayan salt', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'whole spices', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'black pepper powder', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'cream cheese', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'cream cheese', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'cream cheese', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'spring onions', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'whole milk', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'tamarind paste', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'string beans', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'cornstarch', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'pork belly', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'dried red chilies', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'parmesan cheese', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'bread crumbs', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'biryani masala', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'napa cabbage', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'cooking oil', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'lentil', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'organic eggs', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'dry red chiles', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'organic milk', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'anis', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'aniseed', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'bacon', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'mayonnaise', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'peanut oil', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
        DB::table('ingredients')->insert(['ing_name' => 'halal goat meat', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]);
    }
}